theme = 'hugo-bearblog'
baseURL = 'https://jacobcons.github.io/'
languageCode = 'en-us'
title = 'Jacob Cons'

[params]
hideMadeWithLine = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true