theme = 'hugo-bearblog'
baseURL = 'https://jacobcons.com'
languageCode = 'en-us'
title = 'Backend Developer'

[params]
hideMadeWithLine = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true